[project]
name = "livekit-ultra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "deepagents>=0.7.11",
    "elevenlabs>=2.65.0",
    "langchain>=1.3.18",
    "langchain-openai>=1.6.0",
    "langchain-quickjs>=0.3.5",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.11",
    "livekit-agents[elevenlabs,langchain,mcp,silero]>=1.7.0",
    "livekit-plugins-deepgram==1.7.1",
    "livekit-plugins-openai==1.7.1",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.3",
]
